<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>MarketCore.WPF</RootNamespace>
    <AssemblyName>MarketCore.WPF</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MarketCore.csproj" />
    <ProjectReference Include="..\MarketCore.HistoricalImporter\MarketCore.HistoricalImporter.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Npgsql" Version="9.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>
  <ItemGroup>
    <Page Remove="AnaliseQuantitativa\*.backup*" />
    <None Include="AnaliseQuantitativa\*.backup*" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Config\PregaoVivaVoz\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>