<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>MarketCore</AssemblyName>
    <RootNamespace>MarketCore</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="MarketCore.WPF\**" />
    <Compile Remove="MarketCore.HistoricalImporter\**" />
    <Compile Remove="HistoricalImporterTool\**" />
    <None Remove="MarketCore.WPF\**" />
    <EmbeddedResource Remove="MarketCore.WPF\**" />
    <Page Remove="MarketCore.WPF\**" />
    <Resource Remove="MarketCore.WPF\**" />
    <ApplicationDefinition Remove="MarketCore.WPF\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="MarketCore.HistoricalImporter\MarketCore.HistoricalImporter.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ProfitDLL64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.11" />
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.2.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
  </ItemGroup>
</Project>